sspring.application.name=securitydemo

#logging.level.root=DEBUG
#logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.web=DEBUG
## Custom username for the default security user
spring.security.user.name=myuser

# Custom password for the default security user
spring.security.user.password=mypassword
##server.port=0

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test